#!/bin/bash

echo "Cleaning Folder"
mkdir tmp backup_linux
mv *~ backup_linux/.
mv *.aux *.bbl *.blg *.dvi *.log *.nav *.out *.snm *.toc *.lof *.lot tmp/.
mv *concordance.tex *.synctex.gz tmp/.
mv *.Rout tmp/.
echo "Done"
